token: #The Bot's Token
adminrole: #Master Admin roles, separated by spaces
whitelist: #Channel whitelist, separated by spaces

groups: #(NYI) permission groups, and commands they are allowed to use. New groups can be created in the same format
  GroupName1:
    id:
      - groupid1
      - groupid2
    isadmin: False
    permissions:
      - command/permissionid1

users:
  UserName1:
    id: someoneid
    isadmin: False
    permissions:
      - command/permissionid1
      - command/permissionid6
  UserName2:
    id: test
    isadmin: True
    permissions:
      - command/permissionid2
      - command/permissionid3
      - command/permissionid7
