botToken: BOT TOKEN
rebrandlyToken: REBRANDY API KEY
rebrandlyURL: REBRANDY URL
channelWhitelist: NIY

groups:
  AdministerMODERATION:
    groupId:
      - 319607520307970051
      - 320617625300369408
      - 320616748833439744
      - 319606870606217217
    admin: True
    power: 0
    permissions:
      - command.clan
      - command.v
  AdministerUSER:
    groupId:
      - 256137186456371200
    admin: False
    power: 0
    permissions:
      - command.clan
users:
#The Best Guy
  Seth:
    userId: 111592329424470016
    admin: True
    power: 0
  Dragorak:
    userId: 323258668445597696
    admin: False
    power: 0
    permissions:
      - command.m
